spring.application.name=Garage_Management

spring.datasource.url=jdbc:postgresql://localhost:5432/Garage_DB
spring.datasource.username=postgres
spring.datasource.password=Monika05@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=monikabhujbal2004@gmail.com
spring.mail.password=bwmb lkwx uflr iugx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
